### ISSUE TITLE
Sector specific questions seems to have broken the ability to fix shapes

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/next#291]
From @wmcclin 

> User draws invalid shape in recreational fishing but SeaSketch permits her to move forward anyway. Only when submitting her responses to the attributes (sector specific questions) is she prompted to fix her invalid shapes. But, there's no way for her to go back and fix the shape. She can only delete.

**Comment by underbluewaters** [comment]
@wmcclin Are you still seeing this? I can't ever seem to finalize a shape, either by clicking done or clicking away, when it is in an invalid state. Could you take some screenshots or describe step-by-step how you were able to get into this situation?

**Comment by wmcclin** [comment]
I'm not. We made some changes to the sector specific questions. Perhaps that repaired the issue.

**Comment by wmcclin** [comment]
I was able to make it happen again on my iPhone using the Maldives survey, drawing bad shapes for the Research and Conservation tracker. I can save invalid shapes and only when I'm passed along to the attributes dialog am I told that I've drawn an invalid shape (but have no way to fix it). 


![IMG_7323](https://user-images.githubusercontent.com/932832/150214163-0c32de6b-da01-455e-9b67-c93b0fc674c3.PNG)
![IMG_7322](https://user-images.githubusercontent.com/932832/150214171-b6b577b9-3355-4686-883b-2ff27e8a6eff.PNG)
![IMG_7321](https://user-images.githubusercontent.com/932832/150214177-285850f6-bbca-45de-bafe-7acc31c91d6c.PNG)
![IMG_7320](https://user-images.githubusercontent.com/932832/150214180-6487f36e-087c-452f-a58d-1836ffa6cbf5.PNG)

**Comment by underbluewaters** [comment]
I see. It looks like it's only if you use the "Finish Shape" button that you can get into this state. I'll have to add an extra check there.
