### ISSUE TITLE
Providing Informed Consent

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#301]
We are running into the issue of informed consent with the Azores project. Currently, we are looking at having people sign paper forms and tag them in such a way that they can be associated with their response. Facilitators can provide the consent forms, store them and maybe upload them with Legacy SeaSketch. With SeaSketch Next, there's no way for facilitators to upload them and associate them with a response. Unfacilitated respondents currently don't have any means of explicitly giving consent. 

So, would love to add a feature that captures informed consent. What that should look like, I don't know.

**Comment by underbluewaters** [comment]
This will be included in #190
