### ISSUE TITLE
Choosing "facilitated response" changes 

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#303]
In the Maldives OUS, the question, "Which island of R atoll do you reside on?" is a multiple-choice question. However, if the user chooses to submit a "facilitated response", the question changes to a ComboBox.
<img width="492" alt="Screen Shot 2022-01-24 at 6 01 18 AM" src="https://user-images.githubusercontent.com/932832/150796691-3cdd4dbc-0b41-49ab-979a-7a396427e8c8.png">
<img width="485" alt="Screen Shot 2022-01-24 at 6 01 37 AM" src="https://user-images.githubusercontent.com/932832/150796737-8b0bd000-d8ea-4c61-9f41-033c54a838dd.png">

**Comment by wmcclin** [comment]
Hmm. No. Actually, I think it has to do with what the answer is to "Which Atoll do you reside on. Hoosing "HDh" as above, shows you the Multiple Choice view. Choosing "R" shows you the ComboBox.

**Comment by underbluewaters** [comment]
Yep! There's a button in the admin to switch between multiple-choice and combo box. Multiple-choice is a better UI option in most cases, but if the list gets really long it is better to switch to a combobox.

**Comment by wmcclin** [comment]
Ahhh! Right. Thanks.
