### ISSUE TITLE
Switching to Azores Lite Crashes Mobile App

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#309]
On my iPhone 11 Pro, if I switch from the default basemap to Azores lite (in the Blue Azores survey), the app crashes. Switching to the satellite map does not have the same effect.
![IMG_6E7B87498DB2-1](https://user-images.githubusercontent.com/932832/151049613-7004adb1-7a35-455e-8efd-7b7738f52641.jpeg)

**Comment by underbluewaters** [comment]
This is now fixed. It turns out that datasource `mapbox.mapbox-terrain-dem-v1` was in some of our basemaps, which caused Safari to crash. This was totally unrelated to the SeaSketch application itself. I've notified mapbox support and @eryzna updated our basemaps.
