### ISSUE TITLE
AreaCount_plural showing up instead of shape count

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#312]
In the Maldives OUS (and not other projects), "AreaCount_plural" shows up rather than the shape count. 
<img width="928" alt="Screen Shot 2022-01-25 at 6 45 18 PM" src="https://user-images.githubusercontent.com/932832/151101504-137eaf48-dc02-42e4-aa92-b04c90fe1815.png">

**Comment by underbluewaters** [comment]
Do you still see this? I don't. Might be this got fixed in the latest translation update.

**Comment by wmcclin** [comment]
Seems to be fixed! Thanks.

**Comment by wmcclin** [comment]
This issue is still showing up in the Maldives survey. Last night we observed it about 5 times. I believe all users were using Chrome on a variety of Windows-based laptops. 

-W
<img width="529" alt="Screen Shot 2022-01-26 at 9 28 55 PM" src="https://user-images.githubusercontent.com/932832/151422369-8f9e6cdc-28f4-4dcf-8d3e-16c62cf0e24a.png">
<img width="550" alt="Screen Shot 2022-01-26 at 8 40 46 PM" src="https://user-images.githubusercontent.com/932832/151422373-64312747-1e45-440b-9a21-204a500b66c3.png">
<img width="572" alt="Screen Shot 2022-01-26 at 8 20 50 PM" src="https://user-images.githubusercontent.com/932832/151422375-4a7ca872-3511-46b1-a057-37e3525ce022.png">

**Comment by wmcclin** [comment]
Still happening. These are default values from the SAP form used for an example survey in Norway. https://next.seasket.ch/norway/surveys/30/0 


![Screen Shot 2022-02-14 at 1 25 21 PM](https://user-images.githubusercontent.com/932832/153949108-1ef0b6f7-30a7-4c81-9c2e-fbeb05bfafbd.png)
