### ISSUE TITLE
Showing value mismatch error even though values are the same

### ISSUE THREAD

**Issue by madelinemberger** [seasketch/next#315]
This _may_ be a user error but wanted to flag in case not. Getting the values do not match error on one of the Blue Azores pages, but  I checked and even tested the text for matching in  Excel, with all rows back as "TRUE". Even if I did miss the error, wanted to flag that it's somewhat difficult to troubleshoot since the labels / values box does not pop out or widen at all - if that was possible it would be super useful enhancement.

![Screen Shot 2022-01-28 at 4 06 29 PM](https://user-images.githubusercontent.com/32374991/151637837-40943ffd-3e97-400d-886a-ade6ea70962a.png)

**Comment by wmcclin** [comment]
Yeah, I'm seeing the same. I've combed through it a half dozen times, re-entered the values, and I'm getting the same message.
<img width="1491" alt="Screen Shot 2022-01-31 at 8 18 27 AM" src="https://user-images.githubusercontent.com/932832/151831424-89bb166e-ac8e-49b0-8f4b-a08ce988e440.png">

**Comment by underbluewaters** [comment]
Looks like this and #388 might be duplicates

**Comment by underbluewaters** [comment]
Fixed. See #388
