### ISSUE TITLE
Built-in Heatmap Example

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#324]
Currently, all of our projects provide a link to a PDF that shows and describes the OUS fishing heat map for Montserrat. This is to help survey respondents understand how their information will be used.  It would be great if we could have a feature to include this in all of our surveys without (necessarily) a reference to an external document. That way, we can apply custom translations easily and users wouldn't have to use the browser's "back" button to return to survey. 

![Screen Shot 2022-02-14 at 9 40 52 AM](https://user-images.githubusercontent.com/932832/153917274-1b76740e-3146-4557-b7b2-f169cb498f7c.png)
![Screen Shot 2022-02-14 at 9 41 10 AM](https://user-images.githubusercontent.com/932832/153917327-07a98c23-2d82-466e-839b-38a32e421c32.png)

**Comment by underbluewaters** [comment]
This use-case will be addressed by https://github.com/seasketch/next/issues/332
