### ISSUE TITLE
Survey forms can trigger map bookmark

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#327]
We are going to launch surveys that ask users to review and comment on maps (OUS heat maps, zoning scenarios, etc). It would be nice if a question could be tied to a specific map view. For example, a user indicates that she's a fisher, so she is presented with the fishing heat map and a series of questions that pertain to that map only.

**Comment by underbluewaters** [comment]
Closing in favor of https://github.com/seasketch/next/issues/332
