### ISSUE TITLE
Scrolling to review survey responses not working

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#335]
I'm trying to review survey responses in the admin dashboard and I can't scroll down to view more than the first one or two responses.
<img width="1129" alt="Screen Shot 2022-02-28 at 12 14 15 AM" src="https://user-images.githubusercontent.com/932832/155904075-b198cd94-93f6-477b-8632-6bb8a66190a3.png">

**Comment by wmcclin** [comment]
Not an issue. I realized that I was just trying to scroll the whole page (not the table of responses).

**Comment by underbluewaters** [comment]
Scrolling works as intended but the other elements on the screen have a fixed height that then means the scrollable area left for the table is quite short. There’s going to have to be some adaptable layout for laptops. Maybe even resizeable map.
