### ISSUE TITLE
Survey bug: Error when trying to add a sector-specific question and toggle the sector 

### ISSUE THREAD

**Issue by madelinemberger** [seasketch/next#358]
When trying to toggle a sector choice for a question that should only appear for that sector, I get the following error: 

Error: new row for relation "form_elements" violates check constraint "form_fields_component_settings_check"

The toggle also won't go (I switch it, then it bounces back with the error).

**Comment by underbluewaters** [comment]
I'm having a lot of trouble making a generic fix for data that has been corrupted by this issue. I have to fix in on a per-survey basis manually using the following query:

```sql
update form_elements set component_settings = jsonb_set(jsonb_set(component_settings, '{childVisibilitySettings}', '{}'), '{subordinateVisibilitySettings}', '{}') where id = 300;
```

Let me know if there are particular surveys you need me to fix. It *shouldn't* happen on new surveys but please let me know if it crops up again.
