### ISSUE TITLE
Sector-specific visibility toggle switch not sticking. 

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#387]
This question, which is specific to the fisheries sector, isn't showing up because I can't toggle the "sector-specific visibility" and have it stay on. 

https://next.seasket.ch/fsm/survey-editor/35/691
<img width="1460" alt="Screen Shot 2022-06-20 at 1 54 00 PM" src="https://user-images.githubusercontent.com/932832/174676728-87b06930-1022-46e7-a0fb-e1ee32e64f2d.png">

**Comment by underbluewaters** [comment]
Fixed in eeb627f93119305bde9685797c07361b715f3a3e and deployed to production
