### ISSUE TITLE
Scale bar needed for survey maps? 

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#391]
Is there currently a way to add a scale bar to survey maps? This feature was requested several times during my visit to the Maldives.

**Comment by wmcclin** [comment]
Gotcha. Is this something that you could add fairly easily? It's turning out to be fairly urgent because (a) people are taking screenshots of the heatmaps for "final reports" in the Azores, and (b) people are going to be reviewing heatmaps in SNN in the Maldives starting in 2 weeks.

**Comment by underbluewaters** [comment]
Closed in #9b674957ef9dd751d7745d83c87e725043a25b22
