### ISSUE TITLE
Survey only set to English behaving as if it has Divehi (but it does not)

### ISSUE THREAD

**Issue by madelinemberger** [seasketch/next#415]
Working on a survey in the Fiji project that only has English (no other languages toggled) but when I open the edit page, all the text is right justified and the titles of the questions are not showing up in the list (see screen shot). Refresh and hard refresh have not fixed it. When I preview the survey, all the text is right justified and the buttons are in Divehi. 

<img width="685" alt="Screen Shot 2022-08-29 at 8 01 23 AM" src="https://user-images.githubusercontent.com/32374991/187234387-f5cd8942-1813-4186-9bb9-2258af16ff9c.png">

![Screen Shot 2022-08-29 at 8 12 49 AM](https://user-images.githubusercontent.com/32374991/187234438-7acbf5fa-f819-4dcb-94bf-afbc716bae16.png)

**Comment by underbluewaters** [comment]
Fixed in b2ad064303a369b21e73c0a0add4d00f6dd0b0a4. Will be deployed in the next 24 hours
