### ISSUE TITLE
Consent form does not load

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#419]
When clicking on the "Read Full Agreement" link in the Blue Azores OUS (https://next.seasket.ch/blueazores/surveys/23/1), access is denied. 

<img width="941" alt="Screen Shot 2022-09-06 at 10 28 29 AM" src="https://user-images.githubusercontent.com/932832/188701274-100ce2c8-e545-4453-99f5-9308c118d355.png">

**Comment by underbluewaters** [comment]
Was related to an incorrectly set secret in the production environment. Pointed to the wrong cloudfront distribution.
