### ISSUE TITLE
Set basemap default extent is broken

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#426]
<img width="2438" alt="Screen Shot 2022-09-26 at 1 12 36 PM" src="https://user-images.githubusercontent.com/932832/192371665-e7220644-b22d-43b9-9631-1848521683da.png">

**Comment by wmcclin** [comment]
Any chance this feature can be fixed by the end of the week (Oct 7)? We are trying to prepare this survey to be used in an MSP course in Fiji and need to do a little testing with Amanda Ford (Professor) before then.  Right now, we can't create a default view around Fiji where the survey is taking place.

**Comment by underbluewaters** [comment]
I'm pretty sure I fixed this. Please reopen if it comes up again.
