### ISSUE TITLE
Changes to mapbox style sheet not updating in seasketch

### ISSUE THREAD

**Issue by petermenzies** [seasketch/next#428]
I've updated the following style sheet with the Fiji EEZ: mapbox://styles/seasketch/cl8j7q70w001915p6wcgn9pjh, which is labeled "Fiji Light - Will". However the changes are not reflected in the USP project: https://next.seasket.ch/usp/admin/data.

<img width="2032" alt="Screen Shot 2022-10-05 at 1 28 04 PM" src="https://user-images.githubusercontent.com/69406059/194157105-97ca2e65-a55a-4c01-bc9f-ef09386dd92d.png">

**Comment by petermenzies** [comment]
Actually it showed up after several minutes - must've just been a lag.

**Comment by underbluewaters** [comment]
Can take 15 minutes for published changes to work through mapbox's cdn.
