### ISSUE TITLE
Skip logic cannot be specified for non-input elements

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#445]
Skip logic cannot be specified for non-input elements, but is this reasonable? I'm using the survey tool to simply walk people through all of the Azores OUS heatmaps without soliciting input from them. If they select "Flores Island", I want to show them a bunch of maps, one after the other, showing activities around Flores Island. Then, I want to direct them to the "submit" page. However, there's no way for me to do that because there are other forms that follow (and I'd like to skip). 

<img width="1672" alt="Screenshot 2022-11-03 at 2 50 22 PM" src="https://user-images.githubusercontent.com/932832/199841991-b678b04c-58fc-4814-bb89-3ee9fcb6a16e.png">

See https://next.seasket.ch/blueazores/admin/surveys/157

I realize this is a bit of an unintended use of the Survey Tool, but doesn't it make sense that we should be able to skip from any question to the next? Let's discuss.

**Comment by underbluewaters** [comment]
Give that change a try. I haven't tested the actual performance of the skip logic yet when running through a survey but it should be functional now.
