### ISSUE TITLE
Notes Tool

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#446]
Seeing this email from our meeting last night reminded me of how useful it would be to have a note-taking tool in Next. I thought I'd post it hear so you could see the kinds of details that are typically recorded in a meeting where folks are reviewing a draft plan. 

--

**MSP Co-Chairs Meeting | 2022, November 09, 09:00 – 10:00am MVT**

Robin, Andy, Emily, Will, Nisthu, Moosa, Maeesha, Shaistha

Co-chairs: Munshidha, Muhsina, Lisama, Rilwan, Basma, Imad

John presented the draft offshore plan to the co-chairs as a recording
 

**Feedback from co-chairs and responses.**

**Muhsina (MECCT):**

- Are the current proposed sites similar to or different from the proposals from stakeholders, and is there any way to compare what was proposed by all stakeholders and how it was integrated into the current proposal presented today?
- The draft proposal presented to co-chairs began with a proposal developed on August 19th by Ilham in a forum on SeaSketch that depicts a number of MPAs that were developed in response to the goals and objectives, and the team borrowed from that proposal and tried to get closer to protection goals while minimizing displacement to fishers.
- The MECCT co-chair was the only one who submitted a draft proposal; no draft proposals were received from the other co-chairs. Thus, the suggestion was for members of the Noo Raajje/WI/BPC teams who had previously participated in these processes to spend some time within the analytical framework with spatial planning objectives.
- It would be useful to have more information, particularly on migratory species such as whales and other megafauna, as well as information on future development projects such as the bunkering facilities for ships planned in the northern region.
- Will follow up with MED to obtain information on future development projects, such as the bunkering facility.
- What is the implementation plan and cost, as well as the resource mobilization plan (finances, technology, and human development)?
- Discussions with the coastguard are ongoing about how to implement the MSP, but the cost of resource mobilization and other costs have not yet been determined.
- Pablo and Cory will soon begin discussions with MoFMRA about enforcement planning, which is a top priority for the end of this year and the beginning of 2023.

**Munshidha (MoFMRA)**

- For the time being, will the 20% come from the offshore area until the nearshore areas for protection are identified, and how will the bill implement it? There is a provision that until the MSP act is implemented, whatever the co-chairs agree on will be implemented. Does this mean that until the nearshore areas for protection are identified, whatever the co-chairs agree on now will last until the MSP act is implemented?
- Under the bill, we would propose the offshore area first, and we have received direction from the president's office to do so in a phased approach.
- The legal framework is being developed not only for offshore areas, but also for coastal areas, and it allows for a phased approach to planning that will result in a single plan.
- The implementation is process-based, and it has been done in a number of other locations. Its purpose is to allow the process to continue and for the framework to assign a starting point wherever the process is whenever it comes into force. So, once the framework was in place and there was already a draft to work with, the framework implementation would begin by completing the draft consultations, finalizing the draft, and codifying the map-based plan itself, and the same will be true for the nearshore component.

**Lisama (MECCT)**

- In light of the post-2020 global biodiversity framework, which will be adopted in December 2022, we really need to develop some management options. We strongly advocate for the global 30 by 30 target, but some countries have already pledged a national target for 2030 to protect 30% of just their ocean area. It is very likely that the Maldives will pledge to protect only the ocean areas under the post-2020 global biodiversity framework, therefore, suggests incorporating the outcomes of these negotiations, particularly the monitoring framework, headline indicators, and all of these into the management options that we develop for the Maldives' offshore protected areas as well as the nearshore areas that will be protected in the future. The effectiveness of those areas will be important, and there will be a very rigorous national reporting process that comes with the post-2020 global biodiversity framework; therefore, we would like to ensure that we have the capacity to monitor and report on those areas, and that they are effective, and that we can demonstrate that we have protected a certain amount of area within national boundaries that is effectively managed.
- The co-chairs will guide the MSP process in terms of what considerations need to be included and if anything is missing in this initial offshore draft proposal as well.
**The draft offshore plan will be shared with the co-chairs for further deliberation, and the group will hopefully meet next week. Nisthu will find a time that works for everyone for the next meeting.**

**Comment by underbluewaters** [comment]
I think I'm going to close this as we've discussed using the forum as the notes tool. Let's think about (and create issues for) new features that would make the forum wysiwyg editor and sharing tools better for notetaking.
