### ISSUE TITLE
Published metadata doesn't show up until refresh

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#450]
I created some metadata for a layer (Longline Fishing Effort in the FSM project) and published the layers. Returning to the project to view it in the map viewer, the metadata was blank: 
<img width="1556" alt="Screenshot 2022-11-15 at 11 09 47 AM" src="https://user-images.githubusercontent.com/932832/202005444-a2f62ca6-0379-4b65-8559-cbd4a8a80463.png">

Refreshing the page fixed the problem: 
<img width="1556" alt="Screenshot 2022-11-15 at 11 10 09 AM" src="https://user-images.githubusercontent.com/932832/202005626-6485856e-01af-4f23-bd62-e8277ac1ed59.png">

**Comment by underbluewaters** [comment]
Note - the Table of Contents does not update at all after a publish until the browser is refreshed.
