### ISSUE TITLE
Ordering of overlay layers do not match between admin and project view

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#453]
After publishing changes to the overlay layers in the FSM project (next.seasket.ch/fsm), I noticed that the order of folders doesn't match between what I see in the admin view and the project view. 

<img width="1486" alt="Screenshot 2022-11-16 at 4 59 58 PM" src="https://user-images.githubusercontent.com/932832/202328479-913e186c-47ba-4673-aec4-d625a26d27f0.png">
<img width="1486" alt="Screenshot 2022-11-16 at 4 59 39 PM" src="https://user-images.githubusercontent.com/932832/202328490-3b5debba-8616-438c-ac29-aef660ceb67d.png">

**Comment by underbluewaters** [comment]
Looks like order is saving properly in the admin interface. I'm guessing the publishing step isn't copying the sortOrder field.

**Comment by underbluewaters** [comment]
I believe this should be fixed now. Can you see if this works better next time you do a publish @wmcclin?

**Comment by wmcclin** [comment]
Seems to work great! Thanks!
