### ISSUE TITLE
Can't apply viewing permissions to folders

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#457]
I want to limit viewing permissions for a particular folder (Ocean Use Survey) to administrators but that feature isn't available. 

-W
<img width="1759" alt="Screenshot 2022-12-13 at 3 04 33 PM" src="https://user-images.githubusercontent.com/932832/207464004-fb065bc6-3127-4d6d-b64e-a4161dc509b2.png">

**Comment by underbluewaters** [comment]
Added in [38e7c7c](https://github.com/seasketch/next/commit/38e7c7c514c39364d35242e7a1ca97af4cd98b9d)
