### ISSUE TITLE
If sketch is not turned on, choosing "edit" should turn it on. 

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#463]
I wanted to edit an sketch that was not turned on. It zoomed to the extent of the sketch but didn't display the geometry. That was a bit confusing. Seems like choosing "edit" should display the shape. 

<img width="1760" alt="Screenshot 2022-12-20 at 9 23 37 AM" src="https://user-images.githubusercontent.com/932832/208728082-a9517a5d-6694-4b9a-9ee0-2a6b31caef52.png">

**Comment by underbluewaters** [comment]
Fixed but not deployed quite yet.
