### ISSUE TITLE
Error trying to customize survey with image from unsplash

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#465]
Trying to customize a survey with an image from unspash, I get "Error: permission denied for function slugify". This appears to be happening with all projects now. 

<img width="1355" alt="Screenshot 2022-12-28 at 2 29 21 PM" src="https://user-images.githubusercontent.com/932832/209881119-d169d544-8499-4c9e-bb47-bc40bd27f647.png">

**Comment by wmcclin** [comment]
I'm also getting this error when I try to change the "Begin Button Text in Portuguese from the default (Begin) to Começar. 

<img width="850" alt="Screenshot 2022-12-28 at 2 35 13 PM" src="https://user-images.githubusercontent.com/932832/209881256-ac9ed630-213f-4f1f-95ae-23c65a3d1af9.png">

**Comment by wmcclin** [comment]
Oh boy. This appears to effect all kinds of things. I can't even add a Spatial Access Priority question. I get the same error. Any chance this can take priority? I'm supposed to walk through survey building with folks in Brazil tomorrow as part of our prep for the ONR grant.

**Comment by underbluewaters** [comment]
Fixed in the latest deployment.
https://github.com/seasketch/next/commit/10432ab8704f89c97b86095c14eb56030bf54ebc
