### ISSUE TITLE
Need to make the displayed language from the project homepage always English until #517 is implemented

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#472]
When creating a new sketch, or while editing the geometry of an existing sketch, SeaSketch displays instructions in Portuguese - but seemingly only in the FSM project. I don't see this behavior in the Blue Azores or Brazil projects. This could be the weirdest bug ever. :)

<img width="1325" alt="Screenshot 2022-12-29 at 5 05 29 PM" src="https://user-images.githubusercontent.com/932832/210024953-1a798bef-9284-4480-a553-db85f035f0db.png">

**Comment by wmcclin** [comment]
I take it back. It appears to be happening in all of my projects.

**Comment by underbluewaters** [comment]
Need to make the displayed language from the project homepage always English until #517 is implemented.
