### ISSUE TITLE
Only a subset of shapes are included when importing geojson (exported from SSN)

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#473]
I drew two MPAs in Next, placed them into a collection, and then exported this collection to geojson. When viewed in QGIS, both shapes appear: 

<img width="1912" alt="Screenshot 2022-12-29 at 6 03 55 PM" src="https://user-images.githubusercontent.com/932832/210027290-5dce779d-bd7a-46ee-8964-5956ad1c602e.png">

If I import the same file into SeaSketch Next as an overlay layer, the upload succeeds. However, only one of two shapes appears:

<img width="1430" alt="Screenshot 2022-12-29 at 6 08 42 PM" src="https://user-images.githubusercontent.com/932832/210027482-0e794bd4-8a03-4e12-bcb7-35c2fd729615.png">

So, while the exported geojson file includes all of the shapes included in my collection, not all of these shapes are making it into the layer tree.

**Comment by underbluewaters** [comment]
Can you attach the file?

**Comment by wmcclin** [comment]
[Sketch-10865.geojson.json.zip](https://github.com/seasketch/next/files/10325547/Sketch-10865.geojson.json.zip)

**Comment by underbluewaters** [comment]
I think that's the wrong file. This is what I see.

<img width="2387" alt="Screen Shot 2022-12-30 at 9 09 47 AM" src="https://user-images.githubusercontent.com/511063/210096001-3b97c3f5-ec3e-43b0-afa5-9044df352905.png">

**Comment by wmcclin** [comment]
[Sketch-10863.geojson.json.zip](https://github.com/seasketch/next/files/10326358/Sketch-10863.geojson.json.zip)
 
Sorry about that. This is the right file.
