### ISSUE TITLE
Point data in flatgeoguff successfully uploads but not visible on map

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#474]
I was able to successfully upload the attached flatgeobuff files to the Maldives project. However, when I go to view either of them, no points are visible. 

[Seaplanes.fgb.zip](https://github.com/seasketch/next/files/10327733/Seaplanes.fgb.zip)
[Manta_Aggregations.fgb.zip](https://github.com/seasketch/next/files/10327734/Manta_Aggregations.fgb.zip)
<img width="1369" alt="Screenshot 2022-12-31 at 9 33 52 AM" src="https://user-images.githubusercontent.com/932832/210151402-f0bc4221-bd07-4f35-acea-87c584734d33.png">
<img width="1410" alt="Screenshot 2022-12-31 at 9 33 45 AM" src="https://user-images.githubusercontent.com/932832/210151406-86413325-8fe7-49c6-a7de-3eefaa0c0184.png">

**Comment by wmcclin** [comment]
[Resorts.fgb.zip](https://github.com/seasketch/next/files/10377681/Resorts.fgb.zip)

Just tried to upload this again. As it was before, it successfully uploads but the geometries don't show up. The style sheet suggests that Next sees this as as a polygon rather than point geometry.

**Comment by underbluewaters** [comment]
It's an issue with the default style. If you change the style to add a point layer it will work
