### ISSUE TITLE
"Zoom to" the extent of a collection does not work

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#480]
It seems that SSN does not know the proper extent of a collection of sketches. When choosing Zoom To for a collection, the map zooms to a point of the West Coast of Africa. 

<img width="1534" alt="Screenshot 2023-01-18 at 6 40 03 AM" src="https://user-images.githubusercontent.com/932832/212996031-cece4f7c-855e-4386-aa7e-db7add73486b.png">

**Comment by underbluewaters** [comment]
Support added for folders and sketch collections, though it can be a bit off. See #482
