### ISSUE TITLE
Forum messages are slow to update, especially compared to Legacy

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#533]
I've been using the FSM MSP Working Group forum this morning and updates are slow to appear on my screen. I don't think this is an issue with latency in the network. Is there a way to speed up forum updates?

**Comment by underbluewaters** [comment]
There are no real time updates at this point. Best to refresh the browser.

**Comment by wmcclin** [comment]
But they do appear eventually with refreshing. I’ll let them know that they should refresh. --Will McClintockNational Center for Ecological Analysis and SynthesisUniversity of California Santa Barbara, CA 93101On Jan 24, 2023, at 12:31 PM, Chad Burt ***@***.***> wrote:﻿
There are no real time updates at this point. Best to refresh the browser.

**Comment by underbluewaters** [comment]
The topic list gets refreshed every 40 seconds, but it's polling-based rather than responding to actual activity. It's not a huge lift to add realtime updates but it's just not there yet.

**Comment by underbluewaters** [comment]
Realtime updates tasks

- [ ] Add subscription support to graphql server
  - [ ] new posts
  - [ ] new topics
  - [ ] updates to forum and topic stats
- [ ] show new posts immediately in open topic
- [ ] update topic list immediately
- [ ] update forum and topic post counts
