### ISSUE TITLE
Copying individual sketch from forum adds shape to the map, but not the sketch name to the Sketching tab. 

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#542]
If I copy an individual shape that belongs to a collection in a forum, the shape appears on the map but the name of the shape is not added to the Sketching tab. I have to "hide" the orphaned shape. This same problem does not apply to copying entire collections which appears to work just fine. 

<img width="1552" alt="Screenshot 2023-01-25 at 2 45 11 PM" src="https://user-images.githubusercontent.com/932832/214475509-1362c2cf-9441-4282-9fff-47de14bc6d55.png">
<img width="1552" alt="Screenshot 2023-01-25 at 2 45 01 PM" src="https://user-images.githubusercontent.com/932832/214475527-7cb6554e-17d4-4d02-ae09-c8d1832eef6a.png">

**Comment by underbluewaters** [comment]
This should be fixed. Please reopen if you see again.
