### ISSUE TITLE
Auto-expanding folders are cumbersome when filled with lots of items

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#544]
I have a folder that contains lots of sketches, collections and folders that were developed throughout the week. When dragging/dropping items into this folder in attempt to clean up my Sketching Tools tab, I found it problematic to have folders auto-expand. Every time, I had to scroll back up and collapse the folder so that I could return to my task of cleaning up items outside the folder. 

If possible, it would be nice to have folders auto-expand only if I drag an item on top and pause. Otherwise, I'd like the folder to remain closed after dropping in an item. 

<img width="1552" alt="Screenshot 2023-01-27 at 3 11 23 PM" src="https://user-images.githubusercontent.com/932832/215008090-d8b256ec-02e4-42de-8f2e-e7be263fab99.png">

**Comment by underbluewaters** [comment]
I like the idea of expanding on a pause but it's just too hard to choreograph. For now I just disabled expansion on drop and added a little animation that highlights where you dropped the item.
