### ISSUE TITLE
Forum permissions don't appear to extend to reports

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#546]
I'm trying to run a report on a collection that is posted to the MSP Working Group forum without being signed in. The Forum is publicly readable but only working group members can post to the forum. When I run the report, I get the error "Reports not configured". 

Shouldn't I be able to run the reports even though I'm not signed in, given that it's a public forum? 

<img width="1110" alt="Screenshot 2023-01-29 at 10 14 23 AM" src="https://user-images.githubusercontent.com/932832/215295467-3119b971-1e18-42b0-b785-c05f370d60c6.png">

**Comment by underbluewaters** [comment]
Interesting. It's only for collections. MPA-level works fine
