### ISSUE TITLE
Logo Link URL does not work

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#567]
Adding a Logo Link URL under Basic Settings does not create an active link. 

<img width="1216" alt="Screenshot 2023-02-27 at 10 07 24 AM" src="https://user-images.githubusercontent.com/932832/221647101-b2b0f335-e1fb-4850-9651-10415140f493.png">

**Comment by wmcclin** [comment]
Shall we remove this feature? It feels a little weird that one of the first things people are likely to experiment with is broken.

**Comment by underbluewaters** [comment]
Fixed
