### ISSUE TITLE
Forums with long list of threads does not scroll

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#575]
This project has a long list of threads but they can't all be viewed because the window won't scroll. 

https://next.seasket.ch/cms/app/forums/33

<img width="1412" alt="Screenshot 2023-03-21 at 12 12 24 PM" src="https://user-images.githubusercontent.com/932832/226716632-7ebb3d70-1893-41f5-83e0-712e28ca2628.png">

**Comment by underbluewaters** [comment]
Looks like some topics are missing a title too?

**Comment by wmcclin** [comment]
Well, it looks like you can post a new topic without giving it a title but the message content is still there.

**Comment by underbluewaters** [comment]
Fixed in efc2dbf, 7110f1f. Awaiting deployment

**Comment by underbluewaters** [comment]
Deploying: https://github.com/seasketch/next/actions/runs/4483087732

**Comment by underbluewaters** [comment]
Deployed ✅
