### ISSUE TITLE
Lines drawn have weird symbology

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#581]
I'm trying to configure an expedition planning tool for Fiji which includes a sketch class for drawing lines (routes). When I complete the drawing, the symbology appears something like a closed polygon, not a line. 

<img width="1409" alt="Screenshot 2023-04-06 at 12 51 11 PM" src="https://user-images.githubusercontent.com/932832/230481960-a8c91949-f4cc-4918-ad73-9cbd1506f9c8.png">

**Comment by underbluewaters** [comment]
Lines aren't super well supported right now. I'll see if I can make a quick fix for the symbology.
