### ISSUE TITLE
Problems with permissions to sketch classes and forums

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#582]
I'm trying to set permissions on sketch classes and forums so that two groups (staff and expedition planning) have read / write permissions only. After toggling on permissions for these two groups, then clicking away from the dialog box and subsequently returning, the toggles are sometime set to "off" and I get an error: duplicate value violates unique constraint "access_control_list_groups_acess_control_list_id_group_id_key

<img width="1529" alt="Screenshot 2023-04-06 at 1 02 20 PM" src="https://user-images.githubusercontent.com/932832/230483387-14508b67-e9a8-4cee-b9e3-11040e328d9b.png">

The same is tru when configuring permissions for a forum.

**Comment by underbluewaters** [comment]
I only was able to trigger this once out of a dozen tries for some reason. Change to the database function for adding to an access control list should fix it.
