### ISSUE TITLE
Trouble with Sprites

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#584]
I'm having a hard time getting certain sprites to show up as symbols for point data. I've uploaded some sprites that work. Others, don't for reasons that escape me. I also tried cycling through various sprite id's and some work while others don't. The default sprite ID (21) always shows while 49 does not. 

<img width="1912" alt="Screenshot 2023-04-06 at 5 53 15 PM" src="https://user-images.githubusercontent.com/932832/230519081-16274170-ea39-4ca4-b970-c10a2805d154.png">

Here are some sprites I uploaded and that work: 

![Mining_small_green](https://user-images.githubusercontent.com/932832/230519171-b2b4d3da-1201-4b01-ae7a-a035381851fe.png)
![Fish_small_red](https://user-images.githubusercontent.com/932832/230519173-38520a70-082e-493a-a9f0-d0b3e5034988.png)
![Port_Infrastructure_small](https://user-images.githubusercontent.com/932832/230519175-8a5fa922-d589-4847-8c7d-e43837b9a570.png)
![Protection_Shield](https://user-images.githubusercontent.com/932832/230519177-d73f3049-b325-4828-a260-c7d3a71587d4.png)
![buoy_small](https://user-images.githubusercontent.com/932832/230519178-4bd7b21b-455e-4e90-89d7-c258cf3aee5b.png)

Subsequently, I tried uploading these and none of them work (meaning they upload but they don't show up on the map): 

![Caution](https://user-images.githubusercontent.com/932832/230519233-b0c17c96-3135-478b-b83d-067e0931a6f9.png)
![Radio_small](https://user-images.githubusercontent.com/932832/230519234-13798cd6-7d60-4977-8af7-92508300d0bc.png)
![azores_place](https://user-images.githubusercontent.com/932832/230519236-c1d77c70-b218-43e2-876a-2e627b2b4300.png)
![swimming_small](https://user-images.githubusercontent.com/932832/230519239-38525afd-1bc1-4122-b694-e80d3f368ce5.png)

It's almost like the feature to choose custom sprites stopped working.

**Comment by underbluewaters** [comment]
I think Chrome issued an update that changes CORS behavior, so now SeaSketch is having trouble fetching sprites from s3. This will probably take most of today to fix.

**Comment by underbluewaters** [comment]
Fixed by making sprite requests same origin and modifying cloudfront to intercept /sprites directory requests.
