### ISSUE TITLE
New Languages 

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#586]
You'll see that I've added a whole slew of new languages to POEditor and applied automatic translations. Some of these are whimsical (Afrikaans, Arabic, Chinese) while others are going to be used for the Bakul project (French, German, Croatian). When you have a moment, can you add these new languages (and their translations) to SSN?

<img width="1503" alt="Screenshot 2023-04-11 at 10 15 06 AM" src="https://user-images.githubusercontent.com/932832/231239292-a611d580-57c1-4f43-8084-d5f4aecd01c7.png">

**Comment by underbluewaters** [comment]
Deployed.
