### ISSUE TITLE
Linked layers in reports appear to be universally broken

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#601]
I noticed that none of the maps linked in the Samoa project reports (seasketch.org/samoa) seem to be working. All are broken. 
Here's an example collection with reports: https://www.seasketch.org/samoa/app/forums/56/104#post-351

I checked and the same seems to be true for https://seasketch.org/fsm reports. 
<img width="1738" alt="Screenshot 2023-05-18 at 1 10 36 PM" src="https://github.com/seasketch/next/assets/932832/33d927b0-e382-4adf-aa6c-1637821295de">

**Comment by twelch** [comment]
@wmcclin  Layer switching works for FSM and Samoa in seasketch legacy.  It looks like the geoprocessing reference ID's that are set in SSN for each layer don't match what is in the legacy project.  I would guess that they were never set in SSN to match.  I don't think any change on the report side is needed here.  The solution is on the SSN side, and it's to find the legacy layer ID for each layer and paste it into the geoprocessing reference ID field in SSN for each layer to make them match.

<img width="982" alt="image" src="https://github.com/seasketch/next/assets/81816/76282439-cee1-4077-bb42-9ef791c83f73">


<img width="937" alt="image" src="https://github.com/seasketch/next/assets/81816/9e5fadd9-abc3-439a-bfec-0fc0ef44047b">

**Comment by wmcclin** [comment]
Hmm. In the Samoa project, that makes sense. In the FSM project, however, all of the layers were working until yesterday, I think. We had them working during our meeting Pohnpei, for sure, and I frequently have used that project as a demo to show how reports work. I would have shown it a dozen times in Brazil when all of the links worked. 

@twelch are you sure nothing would have changed in the reports in the last couple of days that could have broken those links?

**Comment by twelch** [comment]
@wmcclin these reports haven't been deployed anytime recently and the layer ids are hard coded in the report bundle. if legacy layer toggles still work in the reports then I think it points towards something changing or not being set in ssn.

Cc @underbluewaters

**Comment by underbluewaters** [comment]
Layer toggles were broken by some changes I made to support viewing more that one report at a time. Fix is [here](29ab2e226b5fefed2c721dc1cfe965e0d206b1dc) and being [deployed](https://github.com/seasketch/next/actions/runs/5026588925) right now.

I do notice that Samoa report ids haven't been set at all. The easiest way to update the SSN layer tree would be to copy IDs from the project's [metrics.json file](https://github.com/seasketch/samoa-reports/blob/main/project/metrics.json). FSM project IDs seem to match as expected.
