### ISSUE TITLE
Large points file fails to upload

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#602]
The attached files - one flatgeobuff and the other a shapefile - both fail to upload. The file represents 162,000 depth soundings around Bonaire. Any thoughts as to why this won't upload to Next? 

[iacbaydepth2.fgb.zip](https://github.com/seasketch/next/files/11579879/iacbaydepth2.fgb.zip)
[iacbaydepth.zip](https://github.com/seasketch/next/files/11579883/iacbaydepth.zip)

**Comment by underbluewaters** [comment]
Works now. FGB shouldn't be zipped though.
