### ISSUE TITLE
Attaching documents to forum posts

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#609]
The Maldives (Noo Raajje) project will begin consultations in mid-July through August in which they would like gather data from fishers and councils. Some of the information may come in the form of documents. They'd like to be able attach these documents to a forum post.

**Comment by underbluewaters** [comment]
This could be sort of a big ticket. There are two sides to this work, the upload handling infrastructure and UI pieces.

# UI Side

Prosemirror message documents in the forum support Map Bookmarks via _attachments_, which are designed to support things like File Uploads as well. More details on attachments can be found in the [schema](https://github.com/seasketch/next/blob/master/packages/client/src/editor/config.ts). The basic steps to getting uploads working in forum posts would be:

  * [ ] Extend the [schema](https://github.com/seasketch/next/blob/master/packages/client/src/editor/config.ts) as necessary to store type-specific attachment data.
  * [ ] Add an appropriate action in [EditorMenuBar](https://github.com/seasketch/next/blob/master/packages/client/src/editor/EditorMenuBar.tsx) which calls the appropriate APIs to create the upload record, upload it, and then add the attachment to messages.
  * [ ] Create a ForumFileUpload component to represent uploads in the footer of a message
  * [ ] Update [PostContentEditor](https://github.com/seasketch/next/blob/master/packages/client/src/projects/Forums/PostContentEditor.tsx) to render posted attachments

# Server and Database Support
I'd like to take this opportunity to create a more generic FileUpload table that can be repurposed for other use cases, such as surveys. Like with map_bookmarks, there needs to be some fairly complex introspection of the post prosemirror document to assign the correct post_id to these FileUpload records.

  * [ ] Create a file_uploads table that can be repurposed for surveys and potentially other users
  * [ ] add post-insert/update trigger to posts to assign file_uploads.post_id
  * [ ] implement posts_file_uploads relation
  * [ ] Implement RLS policies as needed
  * [ ] create graphql middleware for embedding access tokens in download links

**Comment by underbluewaters** [comment]
Other tasks
  * [ ] add post-delete trigger and graphile_worker task to delete files from cloud storage
