### ISSUE TITLE
Logic rules appear to limit users to a single option (when multiple options are configured)

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#611]
I have a survey (https://www.seasketch.org/will/surveys/228) in which I ask users to draw shapes and identify if these areas are used for fishing, recreation, shipping, dredging or other using a multiple choice (multiple select) form. If they choose fishing, recreation or other, I want to present them with options for each. For example, if they choose fishing, I want them to indicate the types of fishing. If they ALSO choose recreation, I want them to indicate the types of fishing. I have set up visibility logic and the associated conditional questions. 

However, only a single set of optional questions are presented if the user selects multiple activity types. For exmaple, if I choose "Fishing", the I'm presented with "types of fishing". But, if I choose "Fishing" and "Recreation" I'm only presented with "types of fishing". Can this be fixed so that both sets of conditional questions are revealed to the user? 

<img width="1213" alt="Screenshot 2023-07-04 at 2 55 26 PM" src="https://github.com/seasketch/next/assets/932832/9e107bc4-aa3b-47c9-986b-5b9f2bf37abc">

<img width="1213" alt="Screenshot 2023-07-04 at 2 55 17 PM" src="https://github.com/seasketch/next/assets/932832/7b0176ea-07f2-4814-9ea9-626a4f733060">

<img width="1213" alt="Screenshot 2023-07-04 at 3 04 56 PM" src="https://github.com/seasketch/next/assets/932832/26df8ff4-7375-40a1-a519-a5ce0f2b8626">

<img width="1213" alt="Screenshot 2023-07-04 at 2 53 04 PM" src="https://github.com/seasketch/next/assets/932832/f3d2ba3a-0975-42ac-9b2c-540aed826449">

**Comment by underbluewaters** [comment]
Needed to use contains rather than = operator.
