### ISSUE TITLE
Participation status is not updated, list of accounts in Staff group is incomplete.

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#617]
A user (Ahmed Shimal, 9544556@gmail.com) joined a project (seasketch.org/maldives) after receiving an invitation. He is assigned to the Staff group. His invitation is listed under "Sent Invitations" which shows that he opened the email and that he belongs to the Staff group. 

However, under Participation Status, it says, "Recipient has created an account but has chosen not to join the project and share a public profile. For this reason they will not appear in the participants list or receive any assigned access control permissions." Furthermore, his account does not appear in the list under the Staff group. 

In fact, there are 16 accounts that have been invited and assigned to the Staff group, but on 10 are listed. 

<img width="1481" alt="Screenshot 2023-07-11 at 8 18 10 AM" src="https://github.com/seasketch/next/assets/932832/e943757d-732f-4728-8da3-29ed273b0769">

<img width="1481" alt="Screenshot 2023-07-11 at 8 14 09 AM" src="https://github.com/seasketch/next/assets/932832/5f4ebc2e-b4fd-4b5a-8421-df76022dd9b5">

**Comment by underbluewaters** [comment]
Group lists only show participants who have joined the project and shared a public profile.
