### ISSUE TITLE
Long Forum Messages cannot be posted as New Topic

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#620]
Students have been trying to capture notes during a mock stakeholder meeting using Forums. For new topics, if the message is very long, the "Post New Topic" button becomes inaccessible, lost at the bottom of the message so the message cannot be posted. This does not appear to be a problem if it's a "reply" message. 

<img width="1552" alt="Screenshot 2023-07-20 at 11 56 46 AM" src="https://github.com/seasketch/next/assets/932832/aa83f84e-6aea-4248-bd3d-1976ec5a93ce">

**Comment by underbluewaters** [comment]
Deployment almost done https://github.com/seasketch/next/actions/runs/5612437554
