### ISSUE TITLE
Data layer saved without a name cannot be deleted. 

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#623]
An administrator was changing a title for a layer in seasketch.org/blueazores and somehow managed to save the layer without a name. Now, he can't edit the layer (and rename it) because there is no name to click on. I can't reproduce this issue but, for now, it would be good to programmatically apply a name (even a random one) so we can rename it. 

<img width="1166" alt="Screenshot 2023-07-25 at 1 31 09 PM" src="https://github.com/seasketch/next/assets/932832/7b23a3da-7b45-4f09-ae22-bf64a93b6e86">

**Comment by underbluewaters** [comment]
Fixed in e6eee95bf57ef2b11b7d03e2e2ba166ee82cef7d
