### ISSUE TITLE
Logo Link URL

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#625]
The Logo Link URL saves but doesn't create a link to the image in the project page. 

<img width="1076" alt="Screenshot 2023-08-07 at 12 52 04 PM" src="https://github.com/seasketch/next/assets/932832/fb0235bc-4075-4820-a3c7-3b4db3275cea">
<img width="1025" alt="Screenshot 2023-08-07 at 12 52 16 PM" src="https://github.com/seasketch/next/assets/932832/42a01e92-fe22-4278-a933-b75a4f7fba16">

**Comment by wmcclin** [comment]
Duplicate of #567.

**Comment by underbluewaters** [comment]
Fixed
