### ISSUE TITLE
Metadata and Attribution for Folders

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#627]
It would be great if we can add metadata for folders that include many layers. For example, I have a folder with hundreds of Planet satellite images (in https://seasketch.org/fsm and others). Rather than creating metadata for each layer, I'd love to just hide the children and write metadata for the entire folder. By the same token, it would be great if we could apply attribution for the folder so that, if it's toggled on, the attribution appears at the bottom of the page. 

<img width="741" alt="Screenshot 2023-08-08 at 1 21 35 PM" src="https://github.com/seasketch/next/assets/932832/e63b442b-75c7-49db-9f9c-cd3db2333a8e">

**Comment by underbluewaters** [comment]
I'm not adding Attribution support to hidden folders since that would be redundant. It's only necessary to change the attribution of a single layer to add have that attribution show up for the folder when check on.
