### ISSUE TITLE
Removing a sketch from sketch collection doesn't update updatedAt property

### ISSUE THREAD

**Issue by avmey** [seasketch/next#634]
If I make a sketch collection with 2 sketches in it, then remove one of the sketches from the sketch collection, the updatedAt property of the sketch collection remains the same (and results in an incorrect cache hit). Is this expected?

**Comment by underbluewaters** [comment]
Certainly not expected. I thought that was taken account of. I'll check it out Monday.

**Comment by underbluewaters** [comment]
Fixed in 987fa2edfd0dab3b95bcf69204eecc7eecc3318d
