### ISSUE TITLE
Survey: Changing map settings causes next sector's map to not load

### ISSUE THREAD

**Issue by avmey** [seasketch/next#647]
Attached a gif of the behavior, but to reproduce:
- Start a new survey response and choose more than one sector
- Open a sector, draw and finish a shape
- Open map settings and either change to satellite or use measure tool
- Finish 1st sector
- Open second sector
This second sector's map then doesn't load. 

Refreshing the window works -- it takes you back to the "Your sectors" screen where you can reselect the second sector and the map does load this time.

![Kapture 2023-10-17 at 14 46 22](https://github.com/seasketch/next/assets/22669217/dd322c78-3728-467f-8574-2c2f6fbee2c3)

**Comment by underbluewaters** [comment]
The measurement tools update introduced some instability in loading maps in a few different scenarios, possibly because of upgrading Mapbox GL. I've put in some different mitigations that should avoid crashes.
