### ISSUE TITLE
Cannot retrieve survey responses

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#652]
We have a survey (https://www.seasketch.org/nwmed/surveys/318/0) in which the responses cannot be retried. The error is "Failed to render responses grid". See below. A fix is high priority as this survey will be used in very short order. 

<img width="1519" alt="Screenshot 2023-11-09 at 2 36 05 PM" src="https://github.com/seasketch/next/assets/932832/6016bdd8-dcf9-4958-9af2-ea6bb9ad7ac6">

**Comment by underbluewaters** [comment]
Fixed in cdfac7e
