### ISSUE TITLE
Hide Overlay Layers, Sketching Tools & Forums Tab

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#666]
When no overlay layers, sketching tools or forums have been configured, we should hide those buttons and tabs. The Bermuda MSP Map Viewer (seasketch.org/bermudamsp) requested by Waitt no later than Jan 31 should be "as simple as possible" without extraneous buttons. I envision having only a series of "Maps" without any other tools visible. 

This should be considered high priority. 

<img width="1156" alt="Screenshot 2023-12-13 at 11 33 30 AM" src="https://github.com/seasketch/next/assets/932832/d34e6129-7e8d-4944-9e11-10bbe860e975">

**Comment by underbluewaters** [comment]
I think this may be served by having an explicit setting to hide and show these features since it's difficult to guess at what the intention of the project is by incomplete configuration. Should be a pretty simple addition.

**Comment by underbluewaters** [comment]
Done and deployed.
