### ISSUE TITLE
Scrolling in pop-ups

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#673]
Is it possible to make pop-ups scrollable? It's quite possible that the Bermuda project (seasketch.org/bermuda) will need to have layer popups with tons of detail. 

<img width="1991" alt="Screenshot 2023-12-28 at 8 13 07 AM" src="https://github.com/seasketch/next/assets/932832/8260d46f-8136-4001-be7d-bbeea1e527fa">

**Comment by underbluewaters** [comment]
You can add inline html and style tags to achieve something like that. I’ve had in mind a sidebar overlay interactivity mode that could be used to show more content and that may be more appropriate. Something like what the web version of Google earth and esri storymaps do. It wouldn’t be too hard to get that up and running.
