### ISSUE TITLE
Layer names in the Legend

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#676]
Should layer names in the legend be highlighted somehow, perhaps in bold? I noticed that in cases where layers are symbolized by attributes it's sometimes difficult to distinguish attribute symbology from layer symbology. Notice in the example below that, at first glance, all of the symbols in the legend appear to be based on the layer "Coral Reef Types" when, in fact, they are symbols representing multiple layers. 

<img width="1477" alt="Screenshot 2023-12-29 at 6 58 48 PM" src="https://github.com/seasketch/next/assets/932832/c317f3b7-4a5d-4037-b943-ed122ba91707">

**Comment by underbluewaters** [comment]
I’ll be adding buttons to control opacity and ordering in the legend in the next few weeks. Once that is in and with some design tweaks I think it will be more clear which elements belong to what layers.

**Comment by underbluewaters** [comment]
Fixed in 2affc79a08a273c9f12d9e8a8e79b7807e72cd8d
