### ISSUE TITLE
Layers don't display at some zoom levels

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#677]
I uploaded a bunch of layers to seasketch.org/bermudamsp. For one of them, Coral Reef Types, half of the features don't show up at some zoom levels. 

<img width="2147" alt="Screenshot 2023-12-30 at 5 48 53 PM" src="https://github.com/seasketch/next/assets/932832/f615db18-f638-4280-b846-29e686a828ea">
<img width="2168" alt="Screenshot 2023-12-30 at 5 51 11 PM" src="https://github.com/seasketch/next/assets/932832/62be82db-c414-4ab0-8c82-e78d9a31813d">

**Comment by underbluewaters** [comment]
Tippecanoe will drop features if it can’t simplify them enough to fit under the max tile byte limit. It might help to dissolve and or simplify the data before uploading.
