### ISSUE TITLE
Survery shape deletion issues

### ISSUE THREAD

**Issue by avmey** [seasketch/next#683]
Drawing an area and then pressing "Cancel" brings up popup asking "Are you sure you want to delete this shape?" When confirmed, the screen goes blank and the page needs to be reloaded to continue the survey. The same happens when an invalid shape is drawn and a user tries to delete it using the trash icon.

Additionally, when an invalid shape is drawn, before the shape is completed (vertex double-clicked) a trash icon appears to delete the shape. This icon doesn't function and the shape must be completed before the user can delete it.
<img width="425" alt="Screenshot 2024-01-09 at 12 48 33 PM" src="https://github.com/seasketch/next/assets/22669217/b93f1b72-94a9-4640-9a23-07af45039e30">

Noted in the [Barbados OUS](https://www.seasketch.org/barbados/surveys/342/0).

**Comment by underbluewaters** [comment]
Deploying now: https://github.com/seasketch/next/actions/runs/7465072219
