### ISSUE TITLE
In-progress shape deletion unsuccessful

### ISSUE THREAD

**Issue by avmey** [seasketch/next#686]
When drawing a shape in a survey, if the shape is invalid a note appears declaring the shape invalid with a trash button to delete the shape. This button doesn't function.

![Kapture 2024-01-10 at 11 19 13](https://github.com/seasketch/next/assets/22669217/f4903ce3-d9d2-47bb-9d87-4018251a83f0)

**Comment by underbluewaters** [comment]
Thanks for the gif. Very helpful!
