### ISSUE TITLE
Enable data download should be turned off by default

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#698]
After uploading a new layer, "Enable data download" is toggled on. Administrators should be forced to deliberately turn that on to explicitly indicate that they want data downloadable. 

<img width="1228" alt="Screenshot 2024-02-05 at 7 22 28 AM" src="https://github.com/seasketch/next/assets/932832/83b116ee-7184-4d34-ba9e-c56a42c83b16">

**Comment by underbluewaters** [comment]
this can now be controlled on a project-level setting
