### ISSUE TITLE
Cannot assign attribution for folder of Planet Labs images

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#700]
In the seasketch.org/samoa project there is a folder with a bunch of rasters from Planet.com with "hide children" turned on. I can't edit the folder to assign attribution to any of the layers or enable / disable downloads. If I try to provide attribution to the folder I get an error message. 

<img width="1228" alt="Screenshot 2024-02-05 at 8 03 22 AM" src="https://github.com/seasketch/next/assets/932832/90f4791e-d1ef-4c4e-a07f-49a56ec09f7e">

**Comment by underbluewaters** [comment]
Folders shouldn't have attribution, so it's a bug that some of these fields are showing up in the folder editor. Have you tried setting the attribution on one of the layers? That should work.

**Comment by wmcclin** [comment]
I can't edit the folder. That's a new bug. In the past, yes, I've assigned attribution to one of the layers.
