### ISSUE TITLE
Data downloads disabled but the layers are still downloadable

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#703]
In https://seasketch.org/bahamas, I've uploaded layers (e.g., Slope and Shelf). Although "Enable data download by default" was toggled off, and "Enabled data download" for each of the layers was toggled off, end users can download the data. 

<img width="1588" alt="Screenshot 2024-02-08 at 12 00 06 PM" src="https://github.com/seasketch/next/assets/932832/6f05fb93-e86f-44f0-944b-8396f670e4d6">
<img width="1588" alt="Screenshot 2024-02-08 at 11 59 37 AM" src="https://github.com/seasketch/next/assets/932832/5d055fca-2206-41d5-b319-f18cc52194e0">
<img width="1588" alt="Screenshot 2024-02-08 at 11 59 23 AM" src="https://github.com/seasketch/next/assets/932832/572751bf-957b-4630-aa0a-0315e0b520f8">

**Comment by underbluewaters** [comment]
Going to take another 20 minutes to deploy this. Publishing was stripping away the enable_download setting, and the default is false. Republishing after the update should fix this.

**Comment by underbluewaters** [comment]
Republishing fixed it.
