### ISSUE TITLE
Cartography Tools are Broken

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#722]
I can't symbolize by attribute or view layer properties (attributes) in the cartography editor. 

<img width="1221" alt="Screenshot 2024-03-12 at 2 01 01 PM" src="https://github.com/seasketch/next/assets/932832/e52f2721-a358-416e-ae62-e8436753e3c6">

**Comment by underbluewaters** [comment]
Fixed now. There is a new version of the geostats metadata the system collects which drives this functionality. This somehow got stuck on the old version and wasn't migrated. I *think* I know why and fixed it, but it could crop up again so keep an eye out.
