### ISSUE TITLE
Exported survey responses only contain first value of multi-select multiple choice questions

### ISSUE THREAD

**Issue by petermenzies** [seasketch/next#723]
In a survey, when a multiple choice question has the "Multiple Select" option turned on, responses to that question that have selected multiple values only export with the first selected value.

I first noticed this in the [Fiji OUS](https://www.seasketch.org/fiji/surveys/67/0/) when multiple choice shape attributes were exporting this way. I then did some testing in one of my [sandbox surveys](https://www.seasketch.org/peter/surveys/291/0/) and found this was happening for non-spatial questions as well. In the survey dashboard data viewer I can see the multiple values recorded, despite the exported files not including all the values.

**Comment by underbluewaters** [comment]
Looks like the export utils always coerce these values to a single string. It seems the right thing to do would be to always coerce the value to an array when multiple-select is enabled. Would that break any downstream processing you are doing? I can go ahead and make a fix but I'm hesitant to do so in case I break your apps.
