### ISSUE TITLE
Referrer stats

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#731]
Looking at seasketch.org/brasil, I was comparing the referrer stats for the last 7 days (10 from www.google.com) versus 30 days (none). Doesn't make sense. If there were 10 referrals from Google in the last 7 days, there should be at least that many from the last 30 days. 

<img width="1447" alt="Screenshot 2024-04-13 at 11 22 07 AM" src="https://github.com/seasketch/next/assets/932832/51036116-f564-4e17-a0f8-23ea47be545e">
<img width="1447" alt="Screenshot 2024-04-13 at 11 21 59 AM" src="https://github.com/seasketch/next/assets/932832/81b27ac8-e8db-45f9-9950-cbf5ac62f4fa">

**Comment by underbluewaters** [comment]
I request stats for those 3 different intervals and directly report them verbatim from CloudFlare. I think it's likely that Cloudflare is taking a sampling of events at the 30 day interval and at this low level of visitation we are going to have to accept some inaccuracy.
