### ISSUE TITLE
Legend not showing

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#732]
In https://seasketch.org/california, the legend does not appear when layers are activated. 

<img width="1611" alt="Screenshot 2024-04-15 at 8 29 04 AM" src="https://github.com/seasketch/next/assets/932832/6760e5fe-e0f0-4642-8f80-9b44819619d4">

**Comment by underbluewaters** [comment]
I can't reproduce this. Can you show me exactly what layers are shown? Or try resetting layers.

**Comment by wmcclin** [comment]
Take a look at the image above. I believe the problem is with slow loading Esri map services coming from CDFW. If any of those services are turned on when the app loads, then the legend doesn't appear. Turn those all off, refresh, and the legend appears.

**Comment by underbluewaters** [comment]
There was a debounce function preventing the legend from being updated until all the layers had settled. Now it will wait a maximum of 1 second before redrawing the legend.
