### ISSUE TITLE
Esri service not loading

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#757]
I'm trying to upload an Esri service to seasketch.org/esi. The service URL is: 

https://services2.arcgis.com/C8EMgrsFcRFL6LrL/arcgis/rest/services/Alabama_ESI_2007_test/FeatureServer

SeaSketch finds the service but when I try to add it to my project, SeaSketch hangs on "Evaluating services (4/16)". The service loads fine in Esri's map viewer. 
<img width="1374" alt="Screenshot 2024-07-01 at 9 19 40 AM" src="https://github.com/seasketch/next/assets/932832/88a9f057-c8dd-4831-a00a-794e1b106428">
<img width="1374" alt="Screenshot 2024-07-01 at 9 19 35 AM" src="https://github.com/seasketch/next/assets/932832/41d08130-197d-4da0-bf5e-dad8c79810cb">
<img width="1374" alt="Screenshot 2024-07-01 at 9 19 28 AM" src="https://github.com/seasketch/next/assets/932832/8d75e7f8-111d-46d0-b920-08ff109922a3">

**Comment by underbluewaters** [comment]
Fixed in latest deployment. ArcGIS integration was failing to properly handle switching to tiled requests.
