### ISSUE TITLE
Add feature to constrain values displayed in raster

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#798]
I _think_ this is what's needed to deal with the issue that we're seeing where rasters can't look exactly as they do in QGIS. This refers to the request from Catherine in Kiribati. She wants the rasters shown below to look as they do in QGIS. 
![beru1](https://github.com/user-attachments/assets/a6f7cb46-83e7-4eeb-aaa5-20c60b0ae0e1)
![Beru](https://github.com/user-attachments/assets/b175feaa-cc32-40d2-89f6-819f3f345a79)
[e66ab77f-08cd-4916-bd32-f67f0f4525d0.tif.zip](https://github.com/user-attachments/files/16475898/e66ab77f-08cd-4916-bd32-f67f0f4525d0.tif.zip)

**Comment by underbluewaters** [comment]
This is doable now by unchecking the "show values outside range" option
