### ISSUE TITLE
URGENT: Required survey question does not need to be answered to advance. 

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#802]
In the Yap OUS (https://seasketch.org/fsm/surveys/430), the first map-based question is required. This is the one that asks users to place a point on the map indicating where they live. Although it's required, the user can advance without answering the question. Already, one survey response has been submitted but we do not know where the respondent was from. 

<img width="1624" alt="Screenshot 2024-08-12 at 1 56 47 PM" src="https://github.com/user-attachments/assets/00b1327c-b971-44a8-8bcd-b5d43719aa67">

**Comment by underbluewaters** [comment]
Should be deployed now
