### ISSUE TITLE
NOAA's MPA Inventory Map Service

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#814]
Would like to use this map service in a number of projects:

https://services2.arcgis.com/C8EMgrsFcRFL6LrL/arcgis/rest/services/NOAA_MPA_Inventory_2023/FeatureServer

It's NOAA's MPA Inventory and it loads quickly in the Esri Map Viewer. Unfortunately, I can't import it into a SeaSketch project as it gets stuck on "evaluating services". 

<img width="1779" alt="Screenshot 2024-09-17 at 2 14 48 PM" src="https://github.com/user-attachments/assets/bd53bf07-7d95-4bd3-ac19-21566309632f">

**Comment by underbluewaters** [comment]
Note to self - Timing out after ten seconds. It's quite a large feature service, so it may not complete even if the timeout is removed.
