### ISSUE TITLE
Categorial raster symbology mismatch

### ISSUE THREAD

**Issue by avmey** [seasketch/next#832]
I have a categorical raster with values [0, 1, 2, 30, 31, 32, 100, 101, 102, 200, 201, 202] representing different substrates. SeaSketch accurately finds these values and allows me to set their symbology, but some of the categories aren't showing on the map.

Raster when visualized with QGIS:
<img width="938" alt="Screenshot 2024-10-31 at 9 42 31 AM" src="https://github.com/user-attachments/assets/da4c4efe-fcc2-4191-9072-a516f191cbd6">

Raster when visualized with SeaSketch:
<img width="1101" alt="Screenshot 2024-10-31 at 9 42 59 AM" src="https://github.com/user-attachments/assets/0434066a-0ceb-4f28-8df9-214c321fb515">

**Comment by underbluewaters** [comment]
Fixed
